name: black
on:
  push:
    paths:
      - src/*
      - .github/workflows/black.yml
  pull_request:
    paths:
      - src/*
      - .github/workflows/black.yml
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
