name: codecov
on:
  push:
    paths:
      - src/*
      - .github/workflows/codecov.yml
  pull_request:
    paths:
      - src/*
      - .github/workflows/codecov.yml
jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.11
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Install dependencies
        run: |
          poetry install
      - name: Run tests and collect coverage
        run: poetry run pytest -v --cov ./
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          verbose: true
