name: codecov
on:
  push:
    paths:
      - src/*
      - .github/workflows/codecov.yml
  pull_request:
    paths:
      - src/*
      - .github/workflows/codecov.yml
jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests and collect coverage
        run: pytest -v --cov ./
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          verbose: true
