name: hadolint

on: [push, pull_request]
jobs:
  hadolint:
     runs-on: ubuntu-22.04
     name: "Hadolint"
     steps:
       - uses: actions/checkout@v2
       - uses: jbergstroem/hadolint-gh-action@v1
         with:
           error_level: 0
           annotate: true
           output_format: tty
           dockerfile: ".dockerfile*"
